services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: metrics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: randompw
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: randompw
    ports:
      - "5672:5672"
      - "15672:15672"